%% Search for a specified operating point for the model - AirframeModelTRIM.
%
% This MATLAB script is the command line equivalent of the trim model
% tab in linear analysis tool with current specifications and options.
% It produces the exact same operating points as hitting the Trim button.

% MATLAB(R) file generated by MATLAB(R) 9.4 and Simulink Control Design (TM) 5.1.
%
% Generated on: 11-Apr-2018 13:12:28

%% Specify the model name
model = 'AirframeModelTRIM';

%% Create the operating point specification object.
opspec = operspec(model);

%% Set the constraints on the states in the model.
% - The defaults for all states are Known = false, SteadyState = true,
%   Min = -Inf, Max = Inf, dxMin = -Inf, and dxMax = Inf.

% State (1) - AirframeModelTRIM/Airframe Model/Equations Of Motion/ Equations of Motion (Body Axes)/Position
opspec.States(1).x = [0;-3047.9999];
opspec.States(1).Known = [true;true];
opspec.States(1).SteadyState = [false;false];

% State (2) - AirframeModelTRIM/Airframe Model/Equations Of Motion/ Equations of Motion (Body Axes)/Theta
% - Default model initial conditions are used to initialize optimization.
opspec.States(2).Known = true;
opspec.States(2).SteadyState = false;

% State (3) - AirframeModelTRIM/Airframe Model/Equations Of Motion/ Equations of Motion (Body Axes)/U,w
% - Default model initial conditions are used to initialize optimization.
opspec.States(3).SteadyState = [false;true];

% State (4) - AirframeModelTRIM/Airframe Model/Equations Of Motion/ Equations of Motion (Body Axes)/q
% - Default model initial conditions are used to initialize optimization.

%% Set the constraints on the inputs in the model.
% - The defaults for all inputs are Known = false, Min = -Inf, and
% Max = Inf.

% Input (1) - AirframeModelTRIM/delta
% - Default model initial conditions are used to initialize optimization.

%% Set the constraints on the outputs in the model.
% - The defaults for all outputs are Known = false, Min = -Inf, and
% Max = Inf.

% Output (1) - AirframeModelTRIM/alpha
opspec.Outputs(1).y = 0.17453;
opspec.Outputs(1).Known = true;

% Output (2) - AirframeModelTRIM/V
opspec.Outputs(2).y = 1000;
opspec.Outputs(2).Known = true;

% Output (3) - AirframeModelTRIM/q
% - Default model initial conditions are used to initialize optimization.

% Output (4) - AirframeModelTRIM/az
% - Default model initial conditions are used to initialize optimization.

% Output (5) - AirframeModelTRIM/gamma
% - Default model initial conditions are used to initialize optimization.

% Output (6) - AirframeModelTRIM/h
% - Default model initial conditions are used to initialize optimization.


%% Create the options
opt = findopOptions('OptimizerType','lsqnonlin-proj',...
    'DisplayReport','iter');

%% Perform the operating point search.
[op,opreport] = findop(model,opspec,opt);
